# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jongp2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'Charts'
  pod 'DropDown'
  pod 'Alamofire'
  pod 'StompClientLib'
  # Pods for Jongp2
end
